### ISSUE TITLE
MixinGradle Issue

### ISSUE THREAD

**Issue by EmptyIrony** [asbyth/ForgeTemplate#5]
MixinGradle 6.0 plugin throw exception:
Caused by: java.lang.NoClassDefFoundError: org/gradle/api/internal/file/collections/SimpleFileCollection
	at org.spongepowered.asm.gradle.plugins.MixinExtension$_init_closure4.doCall(MixinExtension.groovy:241)
	at org.spongepowered.asm.gradle.plugins.MixinExtension$_init_closure4.doCall(MixinExtension.groovy)
	at org.spongepowered.asm.gradle.plugins.MixinExtension$_configure_closure13.doCall(MixinExtension.groovy:610)
	at org.spongepowered.asm.gradle.plugins.MixinExtension.configure(MixinExtension.groovy:609)
	at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:484)
	at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:196)
	at org.gradle.internal.metaobject.CompositeDynamicObject.tryInvokeMethod(CompositeDynamicObject.java:98)
	at org.gradle.internal.extensibility.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:34)
	at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:163)
	at org.spongepowered.asm.gradle.plugins.MixinExtension_Decorated.invokeMethod(Unknown Source)
	at org.spongepowered.asm.gradle.plugins.MixinExtension$_applyDefault_closure6.doCall(MixinExtension.groovy:435)
	at org.spongepowered.asm.gradle.plugins.MixinExtension.applyDefault(MixinExtension.groovy:431)
	at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:484)
	at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:196)
	at org.gradle.internal.metaobject.CompositeDynamicObject.tryInvokeMethod(CompositeDynamicObject.java:98)
	at org.gradle.internal.extensibility.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:34)
	at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:163)
	at org.spongepowered.asm.gradle.plugins.MixinExtension_Decorated.invokeMethod(Unknown Source)
	at org.spongepowered.asm.gradle.plugins.MixinExtension$_init_closure1.doCall(MixinExtension.groovy:228)

looks like not support gradle 5.0+
higher MixinGradle version not support forgeGradle below version 3.0

**Comment by asbyth** [comment]
Replace `org.spongepowered:mixingradle:0.6-SNAPSHOT` with `com.github.LXGaming:mixingradle:d75e32e`

**Comment by EmptyIrony** [comment]
its solved,thanks
